//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encryption_App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Encryption_App.DebugResources", typeof(DebugResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual key derivation time: .
        /// </summary>
        internal static string ActualKeyDerivationTime_WriteString {
            get {
                return ResourceManager.GetString("ActualKeyDerivationTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected key derivation time: .
        /// </summary>
        internal static string ExpectedKeyDerivationTime_WriteString {
            get {
                return ResourceManager.GetString("ExpectedKeyDerivationTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copied time: .
        /// </summary>
        internal static string FileCopiedTime_WriteString {
            get {
                return ResourceManager.GetString("FileCopiedTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File write time: .
        /// </summary>
        internal static string FileWriteTime_WriteString {
            get {
                return ResourceManager.GetString("FileWriteTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header removed time: .
        /// </summary>
        internal static string HeaderRemovedTime {
            get {
                return ResourceManager.GetString("HeaderRemovedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivation time: .
        /// </summary>
        internal static string InitialPerformanceDerivationTime_WriteString {
            get {
                return ResourceManager.GetString("InitialPerformanceDerivationTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization time: .
        /// </summary>
        internal static string InitialPerformanceInitializationTime_WriteString {
            get {
                return ResourceManager.GetString("InitialPerformanceInitializationTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password managed time: .
        /// </summary>
        internal static string PasswordControlledTime__WriteString {
            get {
                return ResourceManager.GetString("PasswordControlledTime__WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance value: .
        /// </summary>
        internal static string PerformanceValue_WriteString {
            get {
                return ResourceManager.GetString("PerformanceValue_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post decryption time: .
        /// </summary>
        internal static string PostDecryptionTime_WriteString {
            get {
                return ResourceManager.GetString("PostDecryptionTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post encryption time: .
        /// </summary>
        internal static string PostEncryptionTime_WriteString {
            get {
                return ResourceManager.GetString("PostEncryptionTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post header time: {0}.
        /// </summary>
        internal static string PostHeaderWriteTime_WriteString {
            get {
                return ResourceManager.GetString("PostHeaderWriteTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMAC verified time: .
        /// </summary>
        internal static string PostHMACAuthenticationTime_WriteString {
            get {
                return ResourceManager.GetString("PostHMACAuthenticationTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post authenticate time: .
        /// </summary>
        internal static string PostHMACCreationTime_WriteString {
            get {
                return ResourceManager.GetString("PostHMACCreationTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre decryption time: .
        /// </summary>
        internal static string PreDecryptionTime_WriteString {
            get {
                return ResourceManager.GetString("PreDecryptionTime_WriteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre encryption time: .
        /// </summary>
        internal static string PreEncryptionTime_WriteString {
            get {
                return ResourceManager.GetString("PreEncryptionTime_WriteString", resourceCulture);
            }
        }
    }
}
