//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encryption_App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Encryption_App.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly loaded time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_Assembly_loaded_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_Assembly_loaded_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copied time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_File_copied_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_File_copied_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header removed time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_Header_removed_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_Header_removed_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMAC verified time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_HMAC_verified_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_HMAC_verified_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object built time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_Object_built_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_Object_built_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password managed time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_Password_managed_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_Password_managed_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post decryption time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_Post_decryption_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_Post_decryption_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre decryption time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_Pre_decryption_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_Pre_decryption_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time: .
        /// </summary>
        internal static string MainWindow_DecryptDataWithHeader_Start_time__ {
            get {
                return ResourceManager.GetString("MainWindow_DecryptDataWithHeader_Start_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual key derivation time: .
        /// </summary>
        internal static string MainWindow_EncryptDataWithHeader_Actual_key_derivation_time__ {
            get {
                return ResourceManager.GetString("MainWindow_EncryptDataWithHeader_Actual_key_derivation_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected key derivation time: .
        /// </summary>
        internal static string MainWindow_EncryptDataWithHeader_Expected_key_derivation_time__ {
            get {
                return ResourceManager.GetString("MainWindow_EncryptDataWithHeader_Expected_key_derivation_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File write time: .
        /// </summary>
        internal static string MainWindow_EncryptDataWithHeader_File_write_time__ {
            get {
                return ResourceManager.GetString("MainWindow_EncryptDataWithHeader_File_write_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post authenticate time: .
        /// </summary>
        internal static string MainWindow_EncryptDataWithHeader_Post_authenticate_time__ {
            get {
                return ResourceManager.GetString("MainWindow_EncryptDataWithHeader_Post_authenticate_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post encryption time: .
        /// </summary>
        internal static string MainWindow_EncryptDataWithHeader_Post_encryption_time__ {
            get {
                return ResourceManager.GetString("MainWindow_EncryptDataWithHeader_Post_encryption_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post header time: {0}.
        /// </summary>
        internal static string MainWindow_EncryptDataWithHeader_Post_header_time___0_ {
            get {
                return ResourceManager.GetString("MainWindow_EncryptDataWithHeader_Post_header_time___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre encryption time: .
        /// </summary>
        internal static string MainWindow_EncryptDataWithHeader_Pre_encryption_time__ {
            get {
                return ResourceManager.GetString("MainWindow_EncryptDataWithHeader_Pre_encryption_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivation time: .
        /// </summary>
        internal static string PerformanceTransformer_PerformanceTransformer_Derivation_time__ {
            get {
                return ResourceManager.GetString("PerformanceTransformer_PerformanceTransformer_Derivation_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization time: .
        /// </summary>
        internal static string PerformanceTransformer_PerformanceTransformer_Initialization_time__ {
            get {
                return ResourceManager.GetString("PerformanceTransformer_PerformanceTransformer_Initialization_time__", resourceCulture);
            }
        }
    }
}
